### PR TITLE
Feature Hierarchy extension

### PR DESCRIPTION
**Pull request by lilleyse**
**Note: this extension is not up-to-date with the latest draft of [EXT_feature_metadata](https://github.com/CesiumGS/glTF/pull/1)**

Direct link to extension: [EXT_3dtiles_feature_hierarchy](https://github.com/CesiumGS/glTF/tree/batch-table-hierarchy/extensions/2.0/Vendor/EXT_3dtiles_feature_hierarchy)

This extension is built on top of [EXT_3dtiles_feature_metadata](https://github.com/CesiumGS/glTF/pull/1) to allow for feature classes and metadata hierarchies.

The current 3D Tiles batch table hierarchy spec is [here](https://github.com/CesiumGS/3d-tiles/tree/master/extensions/3DTILES_batch_table_hierarchy). It didn't take too much work to move it to glTF, the only difference is that binary properties can now use glTF accessors. Other changes include:

* The `length` property of a class is renamed to `instanceCount`
* The `instances` property of a class is renamed to `properties` to match the regular feature table
* The `instancesLength` top-level property is renamed to `instanceCount`

Notes:

* I removed the declarative styling section. I think this belongs at a different level of the spec.
* Should this be its own extension or should it be combined into [EXT_3dtiles_feature_metadata](https://github.com/CesiumGS/glTF/pull/1)?
* Needs more well defined behavior when using the same property names across different classes. This is what the spec says now:

> In some cases multiple ancestors may share the same property name. This can occur if two ancestors are the same class or are different classes with the same property names. For example, if every class defined the property "id", then it would be an overloaded property. In such cases it is up to the implementation to decide which value to return.

Instead should properties could be preceded by their class name (e.g. `Building#name` or `Building.name`) to avoid collisions?

@mramato @kring is there anything else that would be nice to have for declarative styling purposes, specifically for the feature hierarchy?

### CODE REVIEW

**Comment by Samulus** [comment]
Maybe change `length` to `instanceCount` ? I think it's clearer (completely subjective).

**Comment by sanjeetsuhag** [comment]
We should be consistent with the glTF naming scheme i.e. use `...length` for size and `...count` for item counts.

**Comment by pjcozzi** [comment]
@lilleyse great to see this.  Please bump to me when ready.

**Comment by lilleyse** [comment]
Renamed the extension to `CESIUM_3diltes_feature_hierarchy` and updated the PR description.

**Comment by lilleyse** [comment]
* [ ] `instanceCount` is used in the class object and in the top level object. Is this ok or should we use a different name?

**Comment by lilleyse** [comment]
Renamed to `EXT_3dtiles_feature_hierarchy` and updated the spec to match the latest changes in https://github.com/CesiumGS/glTF/pull/1#issuecomment-611384278.

**Comment by pjcozzi** [comment]
@lilleyse is this now built into the latest feature metadata extension?  Or will this be a separate extension?

**Comment by lilleyse** [comment]
@pjcozzi this is separate from the metadata extension. I'm going to close this PR since it's out of sync with the latest `EXT_feature_metadata` and the design might change a lot.

**Pull request closed without merging**
